Parameters

```{r params, collapse=TRUE, echo=FALSE}

final <- NULL
pn <- params_names()
pn <- pn [! pn %in% c("data","formula")]

for(i in pn){
  final <- c(final, input[[i]])
}

p <- as.data.frame(matrix(final))
rownames(p) <- pn
colnames(p) <- "Value"
kable(p)
```

URL

```{r url, collapse=TRUE, echo=FALSE}

link <- c()
for(i in pn){
    link <- c(link,"&",i,"=","%22",p[which(rownames(p)==i),1],"%22")
}

if(!is.null(input$funccheck) &&
   input$funccheck == TRUE){
  link <- c(link,"&","anyfunc","=","%22",input$anyfunc,"%22")
}
if((is.null(input$funccheck) ||
    input$funccheck == FALSE)){
  link <- c(link,"&","func","=","%22",input$func,"%22")
}

if(input$func == "bdpsurvival" || input$func == "bdpregression"){
  link <- c(link,"&","Formula","=","%22",input$Formula,"%22")
}

full <- paste0("https://mdic.shinyapps.io/bayesdp/?_inputs_", paste0(link, collapse = ""))

p(a(href=full, "Link back to the shinyapp in the same state as this report."))
```

Print/Summary

```{r print, collapse=TRUE, echo=FALSE}

#summary(final())

print(final())

```

Plots

```{r plots, fig.height=5, echo=FALSE}

if(is.null(input$funccheck) || input$funccheck == FALSE){
  if(input$func == "bdpnormal" ||
     input$func == "bdpbinomial" ||
     input$func == "bdpsurvival"){
    plot(final(), type = "discount")
  }
}

if(is.null(input$funccheck) || input$funccheck == FALSE){
  if(input$func == "bdpnormal" || input$func == "bdpbinomial"){
    plot(final(), type = "posteriors")
  }
}

if(is.null(input$funccheck) || input$funccheck == FALSE){
  if(input$func == "bdpnormal" || input$func == "bdpbinomial"){
    plot(final(), type = "density")
  }
}

if(is.null(input$funccheck) || input$funccheck == FALSE){
  if(input$func == "bdpsurvival"){
    plot(final(), type = "survival")
  }
}

if(!is.null(input$funccheck) && input$funccheck == TRUE){
plot(final())
}

```


